window.IDENGUE_DATA = {
  "latest": {
    "report_date": "2026-09-17",
    "report_date_raw": "17 Sep 2026",
    "epid_year": 2026,
    "epid_week": 37,
    "epid_week_label": "ME 37/2026 (13/09 - 19/09)",
    "epid_week_start": "2026-09-13",
    "epid_week_end": "2026-09-19",
    "cumulative_start_date": "2026-01-04",
    "cumulative_start_raw": "4 Jan 2026",
    "cumulative_end_date": "2026-09-17",
    "cumulative_end_raw": "17 Sep 2026",
    "scraped_at": "2026-09-18T17:41:40.670174+08:00",
    "states": [
      {
        "state": "SELANGOR",
        "daily_cases": 110,
        "cumulative_cases": 29688
      },
      {
        "state": "WILAYAH PERSEKUTUAN",
        "daily_cases": 23,
        "cumulative_cases": 11949
      },
      {
        "state": "JOHOR",
        "daily_cases": 42,
        "cumulative_cases": 11268
      },
      {
        "state": "NEGERI SEMBILAN",
        "daily_cases": 18,
        "cumulative_cases": 4479
      },
      {
        "state": "SABAH",
        "daily_cases": 7,
        "cumulative_cases": 4204
      },
      {
        "state": "PERAK",
        "daily_cases": 3,
        "cumulative_cases": 2139
      },
      {
        "state": "KELANTAN",
        "daily_cases": 6,
        "cumulative_cases": 1601
      },
      {
        "state": "PULAU PINANG",
        "daily_cases": 2,
        "cumulative_cases": 1093
      },
      {
        "state": "PAHANG",
        "daily_cases": 1,
        "cumulative_cases": 782
      },
      {
        "state": "SARAWAK",
        "daily_cases": 3,
        "cumulative_cases": 773
      },
      {
        "state": "KEDAH",
        "daily_cases": 2,
        "cumulative_cases": 690
      },
      {
        "state": "MELAKA",
        "daily_cases": 0,
        "cumulative_cases": 588
      },
      {
        "state": "TERENGGANU",
        "daily_cases": 7,
        "cumulative_cases": 364
      },
      {
        "state": "PERLIS",
        "daily_cases": 0,
        "cumulative_cases": 177
      },
      {
        "state": "WILAYAH PERSEKUTUAN LABUAN",
        "daily_cases": 0,
        "cumulative_cases": 15
      }
    ],
    "total": {
      "state": "MALAYSIA",
      "daily_cases": 224,
      "cumulative_cases": 69810
    }
  },
  "dates": [
    "2026-08-31",
    "2026-09-01",
    "2026-09-02",
    "2026-09-03",
    "2026-09-04",
    "2026-09-05",
    "2026-09-06",
    "2026-09-07",
    "2026-09-08",
    "2026-09-09",
    "2026-09-10",
    "2026-09-11",
    "2026-09-12",
    "2026-09-13",
    "2026-09-14",
    "2026-09-15",
    "2026-09-16",
    "2026-09-17"
  ],
  "daily_matrix": {
    "2026-08-31": {
      "SELANGOR": 94,
      "WILAYAH PERSEKUTUAN": 36,
      "JOHOR": 76,
      "NEGERI SEMBILAN": 13,
      "SABAH": 11,
      "PERAK": 0,
      "KELANTAN": 13,
      "PULAU PINANG": 4,
      "PAHANG": 0,
      "SARAWAK": 4,
      "KEDAH": 2,
      "MELAKA": 4,
      "TERENGGANU": 3,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 260
    },
    "2026-09-01": {
      "SELANGOR": 98,
      "WILAYAH PERSEKUTUAN": 45,
      "JOHOR": 71,
      "NEGERI SEMBILAN": 14,
      "SABAH": 18,
      "PERAK": 12,
      "KELANTAN": 5,
      "PULAU PINANG": 6,
      "PAHANG": 3,
      "SARAWAK": 3,
      "KEDAH": 0,
      "MELAKA": 2,
      "TERENGGANU": 4,
      "PERLIS": 2,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 283
    },
    "2026-09-02": {
      "SELANGOR": 112,
      "WILAYAH PERSEKUTUAN": 65,
      "JOHOR": 64,
      "NEGERI SEMBILAN": 30,
      "SABAH": 20,
      "PERAK": 19,
      "KELANTAN": 16,
      "PULAU PINANG": 5,
      "PAHANG": 10,
      "SARAWAK": 7,
      "KEDAH": 3,
      "MELAKA": 4,
      "TERENGGANU": 3,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 358
    },
    "2026-09-03": {
      "SELANGOR": 124,
      "WILAYAH PERSEKUTUAN": 57,
      "JOHOR": 79,
      "NEGERI SEMBILAN": 22,
      "SABAH": 19,
      "PERAK": 11,
      "KELANTAN": 4,
      "PULAU PINANG": 7,
      "PAHANG": 6,
      "SARAWAK": 4,
      "KEDAH": 0,
      "MELAKA": 1,
      "TERENGGANU": 5,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 339
    },
    "2026-09-04": {
      "SELANGOR": 142,
      "WILAYAH PERSEKUTUAN": 52,
      "JOHOR": 89,
      "NEGERI SEMBILAN": 27,
      "SABAH": 15,
      "PERAK": 9,
      "KELANTAN": 7,
      "PULAU PINANG": 5,
      "PAHANG": 1,
      "SARAWAK": 3,
      "KEDAH": 2,
      "MELAKA": 8,
      "TERENGGANU": 4,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 364
    },
    "2026-09-05": {
      "SELANGOR": 132,
      "WILAYAH PERSEKUTUAN": 42,
      "JOHOR": 87,
      "NEGERI SEMBILAN": 28,
      "SABAH": 11,
      "PERAK": 14,
      "KELANTAN": 1,
      "PULAU PINANG": 7,
      "PAHANG": 5,
      "SARAWAK": 6,
      "KEDAH": 2,
      "MELAKA": 4,
      "TERENGGANU": 3,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 342
    },
    "2026-09-06": {
      "SELANGOR": 124,
      "WILAYAH PERSEKUTUAN": 37,
      "JOHOR": 60,
      "NEGERI SEMBILAN": 14,
      "SABAH": 3,
      "PERAK": 15,
      "KELANTAN": 6,
      "PULAU PINANG": 1,
      "PAHANG": 0,
      "SARAWAK": 1,
      "KEDAH": 1,
      "MELAKA": 0,
      "TERENGGANU": 5,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 267
    },
    "2026-09-07": {
      "SELANGOR": 130,
      "WILAYAH PERSEKUTUAN": 42,
      "JOHOR": 60,
      "NEGERI SEMBILAN": 24,
      "SABAH": 14,
      "PERAK": 11,
      "KELANTAN": 20,
      "PULAU PINANG": 9,
      "PAHANG": 0,
      "SARAWAK": 3,
      "KEDAH": 4,
      "MELAKA": 2,
      "TERENGGANU": 7,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 326
    },
    "2026-09-08": {
      "SELANGOR": 348,
      "WILAYAH PERSEKUTUAN": 98,
      "JOHOR": 127,
      "NEGERI SEMBILAN": 77,
      "SABAH": 30,
      "PERAK": 26,
      "KELANTAN": 16,
      "PULAU PINANG": 12,
      "PAHANG": 8,
      "SARAWAK": 6,
      "KEDAH": 6,
      "MELAKA": 8,
      "TERENGGANU": 14,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 776
    },
    "2026-09-09": {
      "SELANGOR": 197,
      "WILAYAH PERSEKUTUAN": 50,
      "JOHOR": 74,
      "NEGERI SEMBILAN": 25,
      "SABAH": 20,
      "PERAK": 8,
      "KELANTAN": 21,
      "PULAU PINANG": 8,
      "PAHANG": 2,
      "SARAWAK": 7,
      "KEDAH": 3,
      "MELAKA": 10,
      "TERENGGANU": 3,
      "PERLIS": 1,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 429
    },
    "2026-09-10": {
      "SELANGOR": 157,
      "WILAYAH PERSEKUTUAN": 41,
      "JOHOR": 70,
      "NEGERI SEMBILAN": 26,
      "SABAH": 21,
      "PERAK": 14,
      "KELANTAN": 20,
      "PULAU PINANG": 5,
      "PAHANG": 3,
      "SARAWAK": 4,
      "KEDAH": 3,
      "MELAKA": 5,
      "TERENGGANU": 9,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 378
    },
    "2026-09-11": {
      "SELANGOR": 0,
      "WILAYAH PERSEKUTUAN": 0,
      "JOHOR": 0,
      "NEGERI SEMBILAN": 0,
      "SABAH": 0,
      "PERAK": 0,
      "KELANTAN": 0,
      "PULAU PINANG": 0,
      "PAHANG": 0,
      "SARAWAK": 0,
      "KEDAH": 0,
      "MELAKA": 0,
      "TERENGGANU": 0,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 0
    },
    "2026-09-12": {
      "SELANGOR": 118,
      "WILAYAH PERSEKUTUAN": 49,
      "JOHOR": 63,
      "NEGERI SEMBILAN": 21,
      "SABAH": 12,
      "PERAK": 5,
      "KELANTAN": 5,
      "PULAU PINANG": 6,
      "PAHANG": 3,
      "SARAWAK": 5,
      "KEDAH": 0,
      "MELAKA": 4,
      "TERENGGANU": 3,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 294
    },
    "2026-09-13": {
      "SELANGOR": 106,
      "WILAYAH PERSEKUTUAN": 42,
      "JOHOR": 50,
      "NEGERI SEMBILAN": 23,
      "SABAH": 11,
      "PERAK": 10,
      "KELANTAN": 6,
      "PULAU PINANG": 7,
      "PAHANG": 2,
      "SARAWAK": 6,
      "KEDAH": 0,
      "MELAKA": 0,
      "TERENGGANU": 3,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 266
    },
    "2026-09-14": {
      "SELANGOR": 104,
      "WILAYAH PERSEKUTUAN": 26,
      "JOHOR": 57,
      "NEGERI SEMBILAN": 25,
      "SABAH": 15,
      "PERAK": 14,
      "KELANTAN": 10,
      "PULAU PINANG": 2,
      "PAHANG": 4,
      "SARAWAK": 4,
      "KEDAH": 2,
      "MELAKA": 1,
      "TERENGGANU": 8,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 272
    },
    "2026-09-15": {
      "SELANGOR": 134,
      "WILAYAH PERSEKUTUAN": 43,
      "JOHOR": 88,
      "NEGERI SEMBILAN": 29,
      "SABAH": 21,
      "PERAK": 13,
      "KELANTAN": 11,
      "PULAU PINANG": 5,
      "PAHANG": 3,
      "SARAWAK": 6,
      "KEDAH": 3,
      "MELAKA": 5,
      "TERENGGANU": 5,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 366
    },
    "2026-09-16": {
      "SELANGOR": 107,
      "WILAYAH PERSEKUTUAN": 38,
      "JOHOR": 70,
      "NEGERI SEMBILAN": 19,
      "SABAH": 11,
      "PERAK": 11,
      "KELANTAN": 12,
      "PULAU PINANG": 2,
      "PAHANG": 2,
      "SARAWAK": 5,
      "KEDAH": 3,
      "MELAKA": 5,
      "TERENGGANU": 7,
      "PERLIS": 1,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 293
    },
    "2026-09-17": {
      "SELANGOR": 110,
      "WILAYAH PERSEKUTUAN": 23,
      "JOHOR": 42,
      "NEGERI SEMBILAN": 18,
      "SABAH": 7,
      "PERAK": 3,
      "KELANTAN": 6,
      "PULAU PINANG": 2,
      "PAHANG": 1,
      "SARAWAK": 3,
      "KEDAH": 2,
      "MELAKA": 0,
      "TERENGGANU": 7,
      "PERLIS": 0,
      "WILAYAH PERSEKUTUAN LABUAN": 0,
      "MALAYSIA": 224
    }
  },
  "weeks": [
    "2026-W35",
    "2026-W36",
    "2026-W37"
  ],
  "weekly_matrix": {
    "2026-W35": {
      "label": "ME 35/2026 (30/08 - 05/09)",
      "year": "2026",
      "week": "35",
      "states": {
        "SELANGOR": 702,
        "WILAYAH PERSEKUTUAN": 297,
        "JOHOR": 466,
        "NEGERI SEMBILAN": 134,
        "SABAH": 94,
        "PERAK": 65,
        "KELANTAN": 46,
        "PULAU PINANG": 34,
        "PAHANG": 25,
        "SARAWAK": 27,
        "KEDAH": 9,
        "MELAKA": 23,
        "TERENGGANU": 22,
        "PERLIS": 2,
        "WILAYAH PERSEKUTUAN LABUAN": 0,
        "MALAYSIA": 1946
      },
      "totals": {}
    },
    "2026-W36": {
      "label": "ME 36/2026 (06/09 - 12/09)",
      "year": "2026",
      "week": "36",
      "states": {
        "SELANGOR": 1074,
        "WILAYAH PERSEKUTUAN": 317,
        "JOHOR": 454,
        "NEGERI SEMBILAN": 187,
        "SABAH": 100,
        "PERAK": 79,
        "KELANTAN": 88,
        "PULAU PINANG": 41,
        "PAHANG": 16,
        "SARAWAK": 26,
        "KEDAH": 17,
        "MELAKA": 29,
        "TERENGGANU": 41,
        "PERLIS": 1,
        "WILAYAH PERSEKUTUAN LABUAN": 0,
        "MALAYSIA": 2470
      },
      "totals": {}
    },
    "2026-W37": {
      "label": "ME 37/2026 (13/09 - 19/09)",
      "year": "2026",
      "week": "37",
      "states": {
        "SELANGOR": 561,
        "WILAYAH PERSEKUTUAN": 172,
        "JOHOR": 307,
        "NEGERI SEMBILAN": 114,
        "SABAH": 65,
        "PERAK": 51,
        "KELANTAN": 45,
        "PULAU PINANG": 18,
        "PAHANG": 12,
        "SARAWAK": 24,
        "KEDAH": 10,
        "MELAKA": 11,
        "TERENGGANU": 30,
        "PERLIS": 1,
        "WILAYAH PERSEKUTUAN LABUAN": 0,
        "MALAYSIA": 1421
      },
      "totals": {}
    }
  },
  "retrospective_dates": [
    "2026-09-11"
  ]
};